# Generated by Django 5.0.7 on 2024-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_problem_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(default='No expected output provided'),
            preserve_default=False,
        ),
    ]
