# Generated by Django 5.0.7 on 2024-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_problem_expected_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='problem',
            name='input_data',
            field=models.TextField(default='input is not provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
