# Generated by Django 5.0.7 on 2024-07-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
