# Generated by Django 5.0.7 on 2024-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coding_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
