# Generated by Django 5.0.7 on 2024-07-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile_email_profile_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
